### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by Ghost-chu** [nonebot/adapter-dodo#2]
```
11-11 16:02:19 [ERROR] GenshinUID | list index out of range
Traceback (most recent call last):
  File "C:\Users\Ghost_chu\Desktop\BRBot\br-yuanshen-bot\bot.py", line 17, in <module>
    nonebot.run()
  File "C:\Users\Ghost_chu\Desktop\BRBot\br-yuanshen-bot\.venv\Lib\site-packages\nonebot\__init__.py", line 331, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Ghost_chu\Desktop\BRBot\br-yuanshen-bot\.venv\Lib\site-packages\nonebot\drivers\none.py", line 70, in run
    loop.run_until_complete(self._serve())
  File "C:\Users\Ghost_chu\anaconda3\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "C:\Users\Ghost_chu\anaconda3\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Ghost_chu\anaconda3\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\Ghost_chu\anaconda3\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Users\Ghost_chu\anaconda3\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "C:\Users\Ghost_chu\Desktop\BRBot\br-yuanshen-bot\.venv\Lib\site-packages\GenshinUID\client.py", line 274, in recv_msg
    await dodo_send(
  File "C:\Users\Ghost_chu\Desktop\BRBot\br-yuanshen-bot\.venv\Lib\site-packages\GenshinUID\client.py", line 736, in dodo_send
    await _send(content, image)
  File "C:\Users\Ghost_chu\Desktop\BRBot\br-yuanshen-bot\.venv\Lib\site-packages\GenshinUID\client.py", line 724, in _send
    await __send(message)
  File "C:\Users\Ghost_chu\Desktop\BRBot\br-yuanshen-bot\.venv\Lib\site-packages\GenshinUID\client.py", line 692, in __send
    await bot.send_to_channel(
  File "C:\Users\Ghost_chu\Desktop\BRBot\br-yuanshen-bot\.venv\Lib\site-packages\nonebot\adapters\dodo\bot.py", line 138, in send_to_channel
    msg, referenced_message_id = Message(message).to_message_body()
  File "C:\Users\Ghost_chu\Desktop\BRBot\br-yuanshen-bot\.venv\Lib\site-packages\nonebot\adapters\dodo\message.py", line 472, in to_message_body
    last_seg = self[-1]
  File "C:\Users\Ghost_chu\Desktop\BRBot\br-yuanshen-bot\.venv\Lib\site-packages\nonebot\internal\adapter\message.py", line 263, in __getitem__
    return super().__getitem__(arg1)
IndexError: list index out of range
```

**Comment by Ghost-chu** [comment]
该错误每次触发后，aiohttp 框架都需要重新创建一次 websocket 连接，似乎还会导致机器人响应回复速度变得十分迟缓的问题，极端情况下需要7-10秒才能发送出回复。

```
11-12 03:02:04 [WARNING] apscheduler | Run time of job "repeat_connect (trigger: cron[second='*/10'], next run at: 2023-11-12 03:02:10 CST)" was missed by 0:00:04.069036
```

↑ 好像和这个错误有关，每次这个警告都会伴随上面的错误出现，但不知道是不是 dodo adapter 的东西，不过看代码很像是

**Comment by Ghost-chu** [comment]
该错误每次触发后，aiohttp 框架都需要重新创建一次 websocket 连接，似乎还会导致机器人响应回复速度变得十分迟缓的问题，极端情况下需要7-10秒才能发送出回复。

**Comment by CMHopeSunshine** [comment]
a97534f3f04a1937c87f2850e0528098f18638ba 尝试一下0.1.2版本

**Comment by Ghost-chu** [comment]
> [a97534f](https://github.com/nonebot/adapter-dodo/commit/a97534f3f04a1937c87f2850e0528098f18638ba) 尝试一下0.1.2版本

```
Traceback (most recent call last):
  File "C:\Users\Ghost_chu\Desktop\BRBot\br-yuanshen-bot\bot.py", line 17, in <module>
    nonebot.run()
  File "C:\Users\Ghost_chu\Desktop\BRBot\br-yuanshen-bot\.venv\Lib\site-packages\nonebot\__init__.py", line 331, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Ghost_chu\Desktop\BRBot\br-yuanshen-bot\.venv\Lib\site-packages\nonebot\drivers\none.py", line 70, in run
    loop.run_until_complete(self._serve())
  File "C:\Users\Ghost_chu\anaconda3\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "C:\Users\Ghost_chu\anaconda3\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Ghost_chu\anaconda3\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\Ghost_chu\anaconda3\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Users\Ghost_chu\anaconda3\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "C:\Users\Ghost_chu\Desktop\BRBot\br-yuanshen-bot\.venv\Lib\site-packages\GenshinUID\client.py", line 274, in recv_msg
    await dodo_send(
  File "C:\Users\Ghost_chu\Desktop\BRBot\br-yuanshen-bot\.venv\Lib\site-packages\GenshinUID\client.py", line 736, in dodo_send
    await _send(content, image)
  File "C:\Users\Ghost_chu\Desktop\BRBot\br-yuanshen-bot\.venv\Lib\site-packages\GenshinUID\client.py", line 724, in _send
    await __send(message)
  File "C:\Users\Ghost_chu\Desktop\BRBot\br-yuanshen-bot\.venv\Lib\site-packages\GenshinUID\client.py", line 692, in __send
    await bot.send_to_channel(
  File "C:\Users\Ghost_chu\Desktop\BRBot\br-yuanshen-bot\.venv\Lib\site-packages\nonebot\adapters\dodo\bot.py", line 140, in send_to_channel
    await self.set_channel_message_send(
  File "C:\Users\Ghost_chu\Desktop\BRBot\br-yuanshen-bot\.venv\Lib\site-packages\nonebot\internal\adapter\bot.py", line 123, in call_api
    raise exception
  File "C:\Users\Ghost_chu\Desktop\BRBot\br-yuanshen-bot\.venv\Lib\site-packages\nonebot\internal\adapter\bot.py", line 98, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "C:\Users\Ghost_chu\Desktop\BRBot\br-yuanshen-bot\.venv\Lib\site-packages\nonebot\adapters\dodo\adapter.py", line 175, in _call_api
    return await api_handler(bot, **data)
  File "C:\Users\Ghost_chu\Desktop\BRBot\br-yuanshen-bot\.venv\Lib\site-packages\nonebot\adapters\dodo\utils.py", line 63, in __call__
    return await self.func(inst, *args, **kwds)
  File "C:\Users\Ghost_chu\Desktop\BRBot\br-yuanshen-bot\.venv\Lib\site-packages\nonebot\adapters\dodo\bot.py", line 435, in set_channel_message_send
    return parse_obj_as(MessageReturn, await self._request(request))
  File "C:\Users\Ghost_chu\Desktop\BRBot\br-yuanshen-bot\.venv\Lib\site-packages\nonebot\adapters\dodo\bot.py", line 227, in _request
    return self._handle_response(response)
  File "C:\Users\Ghost_chu\Desktop\BRBot\br-yuanshen-bot\.venv\Lib\site-packages\nonebot\adapters\dodo\bot.py", line 212, in _handle_response
    raise ActionFailed(result.status, result.message)
nonebot.adapters.dodo.exception.ActionFailed: <ActionFailed: 10002, 请求参数不允许为空>
```

**Comment by CMHopeSunshine** [comment]
这是预期的，dodo不允许发送空消息，~~包括真实用户也是，聊天框里输入空格按回车发送不出去的~~

**Comment by Ghost-chu** [comment]
> 这是预期的，dodo不允许发送空消息，~包括真实用户也是，聊天框里输入空格按回车发送不出去的~

但是每条消息都发两次，其中一次会失败

11-12 22:28:06 [DEBUG] nonebot | DoDo | Bot 66077028 calling API set_channel_message_send <- 文本消息
11-12 22:28:11 [DEBUG] nonebot | DoDo | Bot 66077028 calling API set_resouce_picture_upload <- 上传图片
11-12 22:28:16 [DEBUG] nonebot | DoDo | Bot 66077028 calling API set_channel_message_send <- 发送了一张图片
11-12 22:28:21 [DEBUG] nonebot | DoDo | Bot 66077028 calling API set_channel_message_send <- 多出来的一次调用

**Comment by Ghost-chu** [comment]
![image](https://github.com/nonebot/adapter-dodo/assets/30802565/fc139e34-6945-43a8-8201-5b3ad1689e85)
能成功发送的消息是按预期的，但是图片消息似乎会多请求一次

**Comment by CMHopeSunshine** [comment]
这应该是插件的行为

**Comment by CMHopeSunshine** [comment]
可以debug一下 `GenshinUID\client.py` 发送消息的相关函数，看是不是多调了次接口

**Comment by Ghost-chu** [comment]
![image](https://github.com/nonebot/adapter-dodo/assets/30802565/e849feea-836b-462d-afa7-b14bfb173216)  
看起来确实是多发送了一条，我会向插件作者反馈，感谢！
